HWA2_webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from blog.views import register
from blog.staticPages import apiPage
from blog.index import index, postEntry, viewEntry, viewUser
from blog.restart import restart

urlpatterns = [
    url(r'^$', index),
    url(r'^home/$', index),
    url(r'^home/(?P<message>[_a-zA-Z]+)/$', index),
    url(r'^view/(?P<num>[0-9]+)/$', viewEntry),
    url(r'^user/(?P<num>[0-9]+)/$', viewUser),
    url(r'^post$', postEntry),
    url(r'^api$', apiPage),
    url(r'^post/(?P<pk>[0-9]+)/$', postEntry),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/', register),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^restart/restart/', restart)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', serve,
                        {"document_root": settings.MEDIA_ROOT, "show_indexes": True})]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class BlogPost(models.Model):
    blog_content = models.TextField()
    blog_title = models.CharField(max_length=200)
    blog_published = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_published = models.DateTimeField()
    date_modified = models.DateTimeField()


class BlogUser(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True)
    profilePicture = models.ImageField(null=True, upload_to="profilePics",
                                       default="profilePics/orange_rect.png")


class BlogComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    content = models.TextField()
    date_published = models.DateTimeField()

polls/models.py
from django.db import models

from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
	
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
	
    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms

class ProfilePhotoForm(forms.Form):
    ## def __init__(self, *args, **kwargs):
    ##    kwargs["label_suffix"] = ""
    ##    super().__init__(self, *args, **kwargs)
    ##    if len(args)==0:
    ##        assert not self.is_bound, str(kwargs)+", "+str(self.__dict__)

    image = forms.ImageField(label="browse", widget=forms.FileInput(attrs={"accept": "image/*"}))

blog/views.py
import re

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import models as authmodels, password_validation, login

from . import viewbase, models


def register(request):
    usererror = emailError = passworderror = password2error = ""
    registerToken = request.POST.get("registerToken", "")
    username = request.POST.get("username", "")
    email = request.POST.get("email", "")
    password = request.POST.get("password", "")
    password_2 = request.POST.get("password_2", "")

    try:
        otheruser = authmodels.User.objects.get(username=username)
        usererror = "Name \"" + username + "\" allready taken"
    except authmodels.User.DoesNotExist:

        usererror = ""

    if re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email) is None:
        emailError = "Invalid email adress"

    try:
        password_validation.validate_password(password, username)
    except password_validation.ValidationError as ex:
        passworderror = ", ".join(ex.messages)

    if password != password_2:
        password2error = "passwords do not match"

    if (usererror == emailError == passworderror == password2error == "" and
                "" not in (username, email, password, password_2, registerToken)):
        user = authmodels.User.objects.create_user(username, email, password)
        user.clean()  # fix email
        user.save()
        login(request, user)

        blogUser = models.BlogUser()
        blogUser.user = user
        blogUser.save()
        return HttpResponseRedirect("/home/registration_completed")

    if registerToken == "":
        emailError = ""
        password2error = ""

    return render(request, 'registration/register.html',
                  {"username": username,
                   "usererror": usererror,
                   "emailerror": emailError,
                   "passworderror": passworderror,
                   "password2error": password2error,
                   "email": email,
                   "password": password,
                   "password2": password_2,
                   **viewbase.viewbase(request)})

# Create your views here.

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/APIdocs.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}API{% endblock %}
{% block title %}API{% endblock %}

{% block content %}
    <h1>Using the API</h1>
    <h2>Basics</h2>
    <p>Accesing a machine-friendly version of the page on this site is as simple as adding <code>?format=json</code>
    to the end of a page name. This works for the main page, user pages, and post pages currently. The output will
    be in json format.</p>
    <p>Some attributes are common among all API requests. These attributes are prefixed with <code>_base</code>. In
    the table below the meaning of these attributes is explained.</p>
    <table>
        <tr>
            <td><code>base_username</code></td><td>The username of the authenticated user, if any</td>
        </tr>
        <tr>
            <td><code>base_user_id</code></td></td><td>The user id of the autheticated user, if such a user exists</td>
        </tr>
        <tr>
            <td><code>base_user_image</code></td><td>The link to the profile picture of the authenticated user, if it
            exists</td>
        </tr>
    </table>
    <h2>Working with post summaries</h2>
    <p>Both user and index pages are basically sets of post summary objects. The summaries can be accesed with the posts
    attribute, which represents a collection of posts. The following attributes are available:</p>
    <table>
        <tr>
            <td><code>summary</code></td><td>The first 500 words of the post</td>
        </tr><tr>
            <td><code>authorid</code></td><td>The ID of the author</td>
        </tr><tr>
            <td><code>authorname</code></td><td>The name of the author</td>
        </tr><tr>
            <td><code>authorimage</code></td><td>A link the profile picture of the author</td>
        </tr>
        <tr>
            <td><code>postid</code></td><td>The ID of the linked post</td>
        </tr>
    </table>
    <p>One can easily get the full post contents by going to <code>/post/&lt;postid&gt;/?format=json</code>, and
    to the author's page by browsing to <code>/user/&lt;authorid&gt;/?format=json</code>.</p>
    <h2>Post details</h2>
    <p>The details post gives detailed information about a post, including it's full content and comments. This
    includes 10 attributes, as seen in the table below:</p>
    <table>
        <tr>
            <td><code>content</code></td><td>The full content of the post, formatted as HTML</td>
        </tr>
        <tr>
            <td><code>title</code></td><td>The title of the post</td>
        </tr>
        <tr>
            <td><code>pubdate</code></td><td>Human readable date when the post was first published, ex: "3 days ago"
            or "Just now"</td>
        </tr>
        <tr>
            <td><code>pubdate_raw</code></td><td>The raw date when the post was first published,
            ex "2017-12-05 14:25:27.046899+00:00"</td>
        </tr>
        <tr>
            <td><code>moddate</code></td><td>The date the post was last modified, human readable, ex "Yesterday"</td>
        </tr>
        <tr>
            <td><code>moddate_raw</code></td><td>The raw date when the post was last modified, in long UTC format</td>
        </tr>
        <tr>
            <td><code>authorimage</code></td><td>A link to the profile picture of the author</td>
        </tr>
        <tr>
            <td><code>authorid</code></td><td>The ID of the author of the post</td>
        </tr>
        <tr>
            <td><code>post_id</code></td><td>The ID of the current post</td>
        </tr>
        <tr>
            <td><code>comments</code></td><td>A list of comments for the current post, see below.</td>
        </tr>
    </table>
    <p>
        Comments is a JSON list of comments. Below is the list of attributes of a comment:
    </p>
    <table>
        <tr>
            <td><code>Content</code></td><td>The contents of the comment</td>
        </tr>
        <tr>
            <td><code>postdate</code></td><td>Human readable date posted</td>
        </tr>
        <tr>
            <td><code>postdate_raw</code></td><td>the date the comment was posted in raw format</td>
        </tr><tr>
            <td><code>author</code></td><td>The username of the author</td>
        </tr>
        <tr>
            <td><code>image</code></td><td>The profile picture of the author</td>
        </tr>
    </table>
    <h2>Logging in</h2>
    <p>Logging in from an API is not trivial as the whole system has CSRF protection. You
    will need a state-preserving session sytem between requests, to keep cookies.
    In order to get your first, temporary CSRF token, send a GET request to
        <code>/accounts/login</code>. The token will be saved in the cookie
        <code>csrftoken</code>. Every post request must have the header
        <code>X-CSRFToken</code> set to the token value. Note that the value
    changes occasionally, so make sure you use the most recent token.</p>
    <p>
        In order to actually log in, sent a POST request to
        <code>/accounts/login</code>, with post arguments <code>username</code>
        and <code>password</code> as the URLencoded post data. This will
        generally give you a new, authenticated sessionID and CSRFtoken.
    </p>
    <h2>Posting</h2>
    <p>
        Posting is done via a POST request to <code>/post?format=json</code>.
        posting requires valid login cookies, and a valid CSRF header,
        see above.
        The following argument are required:
    </p>
    <table>
        <tr><td><code>pubType</code></td><td>Should be "publish"</td></tr>
        <tr><td><code>title</code></td><td>the title of the blog</td></tr>
        <tr><td><code>content</code></td><td>The content of the post, line breaks should be windows style, <code>\r\n</code>,
            a double line break is a paragraph</td></tr>
    </table>
    <p>
        The return value will be a redirect to the view page for the published blog.
    </p>
    <p>
        Currently, there are no countermeasures to prevent spamming, and
        you could potentially flood the whole site with spam with this method.
        Please don't.
    </p>
    <h2>Posting comments</h2>
    <p>
        Comments also require a valid login and CSRF header. POST
        requests should be sent to <code>/view/&lt;postid&gt;</code>
        The only required parameter is <code>comment_content</code>.
        Other properties like date and author are set automatically.
    </p>
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/newPost.js' %}" defer></script>
{% endblock %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}
		{% endblock %}</title>
		<script src="{% static 'scripts/jquiry.js' %}" defer></script>
		{% block scripts%}
		{% endblock %}
		<link rel="stylesheet" href="{% static 'blog/style.css' %}">
	</head>
	<body>
		<div class="page-header">
			<h1><a href="/">
				{% block heading %}
				{% endblock %}
			</a></h1>
		</div>
		<div class="user-info">
			{% if base_username %}
			<span>
				<a href="/user/{{ base_user_id}}" class="user-info-link">
				  <div>{{ base_username }}</div>
				  <img class="user-info-image" src="{{ base_user_image }}"/>
				</a>
				<div><a href="/accounts/logout">log out</a></div></span>
			{% else %}
			<span><div>Not logged in</div>
			      <div><a href="/accounts/login">log in</a></div></span>
			{% endif %}
		</div>
		<div class="content">
			{% block content %}
			{% endblock %}
		</div>

		<div class="footer">
			Made for the 2017 TU/e 2ID60 Web technology webapp assignment.
		</div>
	</body>
</html>

blog/templates/includes/comment.html
<div class="comment">
    <div class="commentauthor">
        <img class="authorimage" src="{{ comment.image }}" alt="{{ comment.author }}"/>
        <span class="authorname">{{ comment.author }}</span><br>
        <span class="dateposted">{{ comment.postdate }}</span>
    </div>
    <span class="commentcontent">
    {{ comment.content }}</span>
</div>

blog/templates/includes/postSummary.html
<div class="postsummary" id="post_{{ post.postid }}">
    <div class="authorinfo">
        <img class="authorimage" src="{{ post.authorimage }}" alt="{{ post.authorname }}"/>
        <span class="authorname">{{ post.authorname }}</span>
    </div>
    <h1 class="posttitle">{{ post.title }}</h1>
    <span class="postcontent">
    {{ post.summary }}</span>
</div>

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}Home{% endblock %}
{% block title %}Home{% endblock %}

{% block content %}
{% if message %}
<div id="message">{{ message }}</div>
{% endif %}
<h1>Newest blog posts</h1>
{% if base_username %}
<div class="flex">
    <a href="/post" class="button">Post new blog</a>
    <a href="/api" class="button">API docs</a>
</div>
{% endif %}

{% for post in posts %}
    {% include "includes/postSummary.html" %}
{% endfor %}

{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/home.js' %}" defer></script>
{% endblock %}

blog/templates/newPost.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}New post{% endblock %}
{% block title %}New post{% endblock %}

{% block content %}
{% if preview %}
    <h1>Preview</h1>
    {% autoescape off %}
    {{ preview }}
    {% endautoescape %}
{% endif %}
<h1>Post new entry</h1>
<form method="POST" autocomplete="off">
    {% csrf_token %}
    <input type="hidden" name="pubType" id="id_pubType" value="publish"/>
    {% if postID %}
    <input type="hidden" name="editID" value="{{ postID }}"/>
    {% endif %}
    <p><label for="id_title">Title</label>
    <input type="text" name="title" id="id_title" value="{{ postTitle }}"/></p>
    <label for="id_content">Content</label>
    <textarea name="content" id="id_content">{{ postContent }}</textarea>
    <div class="flex">
        <button type="submit" id="publish">Publish</button>
        {% if not published %}
        <button type="submit" id="draft">Save draft</button>
        {% endif %}
        <button type="submit" id="preview">Preview</button>
    </div>
</form>
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/newPost.js' %}" defer></script>
{% endblock %}

blog/templates/viewPost.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="posttitle">{{ title }}</h1>
<div class="context">
    <img src="{{ authorimage }}"/><br/>
    <small>Author:</small><br/>
    <a class="authorname" href="/user/{{authorid}}">{{ authorname }}</a><br/>
    <small>Date published:</small><br/>
    <span class="pubdate">{{ pubdate }}</span>
    {% if pubdate != moddate %}
    <br/>
    <small>Last modified:</small><br/>
    <span class="moddate">{{ moddate }}</span>
    {% endif %}
</div>
<article>
    {% autoescape off %}
    {{ content }}
    {% endautoescape %}
</article>
{% if base_username == authorname %}
    <a href="/post/{{ post_id }}" class="button">Edit post</a>
{% endif %}
<div class="comments">
    <h1>{{ comments|length }} comment{% if comments|length != 1 %}s{% endif %}</h1>
    {% for comment in comments %}
        {% include "includes/comment.html" %}
    {% endfor %}
    {% if base_username %}
        <form method="POST">
            {% csrf_token %}
            <textarea name="comment_content"></textarea>
            <button type="submit">Post comment</button>
        </form>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

blog/templates/viewUser.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}Home{% endblock %}
{% block title %}Home{% endblock %}

{% block content %}
<h1>{{username}}</h1>
<div class="pictureframe">
    {% if photo %}
    <img src="{{ photo }}">
    {% else %}
    <img src=https://i.stack.imgur.com/WmvM0.png">
    {% endif %}
    {% if base_username == username %}
    <form method="POST" id="profilePicForm" enctype="multipart/form-data"
          {% if not profileform.is_bound %} style="display: none;"{% endif %}>
        {% csrf_token %}
        {{ profileform }}
    </form>
    {% if not profileform.is_bound %}
    <a href="#" id="changeProfilePic" class="button">Edit picture</a>
    {% endif %}
    {% endif %}
</div>
<h2>Top posts</h2>
{% for post in posts %}
    {% include "includes/postSummary.html" %}
{% endfor %}
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/home.js' %}" defer></script>
{% if base_username == username %}
    <script src="{% static 'scripts/viewUser.js' %}" defer></script>
{% endif %}
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ol>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>